# Generated by Django 3.2 on 2023-01-25 22:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('userName', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30, null=True)),
                ('spacificTitle', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=130)),
                ('currently_job_title', models.CharField(max_length=130)),
                ('date_reviced_title', models.DateField(null=True)),
                ('targeted_title', models.CharField(max_length=30)),
                ('request_status', models.CharField(default='New', max_length=50)),
                ('validation_date', models.DateField()),
                ('requested_date', models.DateField(default=django.utils.timezone.now)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='user.usersdata')),
            ],
        ),
        migrations.CreateModel(
            name='FilesForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('files_path', models.FileField(blank=True, null=True, upload_to='files/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usersinfo')),
            ],
        ),
    ]
