# Generated by Django 3.2 on 2023-02-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='spacificTitle',
            field=models.CharField(default='', max_length=30),
        ),
    ]
