# Generated by Django 3.2 on 2023-01-01 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
